### ISSUE TITLE
Incorrect reporting of individual BLEU scores

### ISSUE THREAD

**Issue by wboag** [hao-fang/mscoco_caption_eval#1]
When examining individual BLEU scores, a logical error in bleu_scorer.py is propogated up into cocoEvalCapDemo.py. Here are the two input json files I used for replicating the bug. They contain two data examples, each example contains a single ground truth reference. Note that such a small amount of data causes problems for the CIDEr and METEOR scorers, so they must be disabled in order to run this demo. Further, do not try to display these images, because I don't have them stored in the jsons.

http://www.cs.uml.edu/~wboag/research/metrics/annotations-bug.json
http://www.cs.uml.edu/~wboag/research/metrics/result-bug.json

When I examine the individual BLEU scores, I get the following information (formatted by me):

    Example 1
    GOLD: A man gets chased by a stampede of people .
    CANDIDATE: A man is riding a dog .
        Bleu_4     0.000135
        Bleu_3     0.000006
        Bleu_2     0.447214
        Bleu_1     0.500000

    Example 2
    GOLD: A man is playing a guitar .
    CANDIDATE: A man is playing a guitar .
        Bleu_4     0.000135
        Bleu_3     0.000006
        Bleu_2     0.447214
        Bleu_1     0.500000

As you can see, Example 2 is a perfect match and should be getting a score of 1.0 for every BLEU. Instead, it's scores are copies of the scores from Example 1. This can be traced back to bleu_scorer.py on lines 224-229

    for key in ['guess','correct']:
        for k in xrange(n):
            totalcomps[key][k] += comps[key][k]
            # append per image bleu score
            bleu_list[k].append( ( ( float(comps['correct'][k]) + tiny) \
                                           /(float(comps['guess'][k]) + small ) ) ** (1./(k+1.)) )

This code should instead look like:

    for key in ['guess','correct']:
        for k in xrange(n):
            totalcomps[key][k] += comps[key][k]
    
    for k in xrange(n):
        # append per image bleu score
        bleu_list[k].append( ( ( float(comps['correct'][k]) + tiny) \
                                       /(float(comps['guess'][k]) + small ) ) ** (1./(k+1.)) )

The individual scores are stored in bleu_list, which were being appended twice in the old version of the code (once for key='guess' and again for key='correct'). This caused bleu_list to look like:

    [[0.4999999999166668, 0.4999999999166668, 0.9999999998333334, 0.9999999998333334], [0.4472135954552368, 0.4472135954552368, 0.9999999999000001, 0.9999999999000001], [6.299605248949403e-06, 6.299605248949403e-06, 0.9999999999166668, 0.9999999999166668], [0.00013512001546944343, 0.00013512001546944343, 0.9999999999166668, 0.9999999999166668]]

instead of what it should look like:

    [[0.4999999999166668, 0.9999999998333334], [0.4472135954552368, 0.9999999999000001], [6.299605248949403e-06, 0.9999999999166668], [0.00013512001546944343, 0.9999999999166668]]

This meant that the first two values for BLEU_1 were 0.4472135954552368 and its copy 0.4472135954552368. It never assigns the 0.9999999999000001 to Example 2 like it should. The proposed change would fix that.

I can elaborate further on this if need be.

**Comment by hao-fang** [comment]
Thanks for pointing out this bug. Actually, the project has been migrated to https://github.com/tylin/coco-caption, where this bug has been fixed. Please refer to the new repository for the evaluation codes.
We are going to remove this old repo hosted on my account to avoid further confusion.

Thanks again for your attention.

Best,
Hao
